
from typing import Any, Self, TypeVar, Generic, Iterator, Type, Tuple, Sequence, Iterable, overload, TypeAlias, Literal
from AppKit import NSBezierPath

NSLineCapStyle = int
NSLineJoinStyle = int
NSCompositingOperation = int
NSTextAlignment = int
NSRectEdge = int
NSAlignmentOptions = int

NSMinXEdge: NSRectEdge
NSMinYEdge: NSRectEdge
NSMaxXEdge: NSRectEdge
NSMaxYEdge: NSRectEdge

_FieldT = TypeVar("_FieldT")

class _NSStruct(Generic[_FieldT]):
	"""A mutable PyObjC struct; indexable & iterable over its fields."""
	def __getitem__(self, key: int) -> _FieldT: ...
	def __len__(self) -> int: ...

class NSPoint(_NSStruct[float]):
	"""A point (x & y)."""
	x: float
	y: float
	def __init__(self, x: float = ..., y: float = ...) -> None: ...

NSPointLike: TypeAlias = "NSPoint | tuple[float, float]"

class NSSize(_NSStruct[float]):
	"""A size (width & height)."""
	width: float
	height: float
	def __init__(self, width: float = ..., height: float = ...) -> None: ...

NSSizeLike: TypeAlias = "NSSize | tuple[float, float]"

class NSRect(_NSStruct["NSPoint | NSSize"]):
	"""A rectangle, defined by origin & size."""
	origin: NSPoint
	size: NSSize
	def __init__(self, origin: NSPointLike = ..., size: NSSizeLike = ...) -> None: ...
	@overload
	def __getitem__(self, key: Literal[0]) -> NSPoint: ...
	@overload
	def __getitem__(self, key: Literal[1]) -> NSSize: ...
	def __iter__(self) -> Iterator[NSPoint | NSSize]: ...

NSRectLike: TypeAlias = "NSRect | tuple[NSPointLike, NSSizeLike]"

class NSRange(_NSStruct[int]):
	"""A range, defined by location & length."""
	location: int
	length: int
	def __init__(self, location: int = ..., length: int = ...) -> None: ...

NSRangeLike: TypeAlias = "NSRange | tuple[int, int]"

def NSMakePoint(x: float, y: float) -> NSPoint: ...
def NSMakeSize(width: float, height: float) -> NSSize: ...
def NSMakeRect(x: float, y: float, width: float, height: float) -> NSRect: ...
def NSMakeRange(location: int, length: int) -> NSRange: ...
def NSInsetRect(rect: NSRectLike, x: float, y: float) -> NSRect: ...
def NSPointInRect(point: NSPointLike, rect: NSRectLike) -> bool: ...
def NSOffsetRect(aRect: NSRectLike, dX: float, dY: float) -> NSRect: ...
def NSIntersectsRect(aRect: NSRectLike, bRect: NSRectLike) -> bool: ...
def NSContainsRect(aRect: NSRectLike, bRect: NSRectLike) -> bool: ...
def NSIsEmptyRect(rect: NSRectLike) -> bool: ...
def NSUnionRect(aRect: NSRectLike, bRect: NSRectLike) -> NSRect: ...
def NSIntersectionRect(aRect: NSRectLike, bRect: NSRectLike) -> NSRect: ...
def NSIntegralRect(rect: NSRectLike) -> NSRect: ...
def NSIntegralRectWithOptions(rect: NSRectLike, options: NSAlignmentOptions) -> NSRect: ...
def NSMouseInRect(aPoint: NSPointLike, aRect: NSRectLike, flipped: bool) -> bool: ...
def NSEqualPoints(aPoint: NSPointLike, bPoint: NSPointLike) -> bool: ...
def NSEqualSizes(aSize: NSSizeLike, bSize: NSSizeLike) -> bool: ...
def NSEqualRects(aRect: NSRectLike, bRect: NSRectLike) -> bool: ...
# PyObjC returns the two out-parameters as a tuple; pass None for both.
def NSDivideRect(inRect: NSRectLike, slice: None, rem: None, amount: float, edge: NSRectEdge) -> Tuple[NSRect, NSRect]: ...
NSZeroRect: NSRect
NSZeroPoint: NSPoint
NSZeroSize: NSSize

def NSMaxRange(range: NSRangeLike) -> int: ...
def NSLocationInRange(loc: int, range: NSRangeLike) -> bool: ...
def NSEqualRanges(range1: NSRangeLike, range2: NSRangeLike) -> bool: ...
def NSUnionRange(range1: NSRangeLike, range2: NSRangeLike) -> NSRange: ...
def NSIntersectionRange(range1: NSRangeLike, range2: NSRangeLike) -> NSRange: ...

def NSStringFromPoint(aPoint: NSPointLike) -> str: ...
def NSStringFromSize(aSize: NSSizeLike) -> str: ...
def NSStringFromRect(aRect: NSRectLike) -> str: ...
def NSStringFromRange(range: NSRangeLike) -> str: ...
def NSPointFromString(aString: str) -> NSPoint: ...
def NSSizeFromString(aString: str) -> NSSize: ...
def NSRectFromString(aString: str) -> NSRect: ...
def NSRangeFromString(aString: str) -> NSRange: ...

def NSMinX(rect: NSRectLike) -> float: ...
def NSMinY(rect: NSRectLike) -> float: ...
def NSMidX(rect: NSRectLike) -> float: ...
def NSMidY(rect: NSRectLike) -> float: ...
def NSMaxX(rect: NSRectLike) -> float: ...
def NSMaxY(rect: NSRectLike) -> float: ...
def NSWidth(rect: NSRectLike) -> float: ...
def NSHeight(rect: NSRectLike) -> float: ...


SEL = Any

def NSSelectorFromString(name: str) -> SEL: ...


class NSObject:
	@classmethod
	def new(cls) -> Self: ...
	@classmethod
	def alloc(cls) -> Self: ...
	def init(self) -> Self: ...
	def copy(self) -> Self: ...
	def description(self) -> str: ...
	def retain(self) -> Self: ...
	def release(self) -> None: ...
	def className(self) -> str: ...

	def valueForKey_(self, key: str) -> Any: ...
	def performSelector_withObject_afterDelay_(self, sel: SEL, obj: Any, delay: float) -> None: ...
	def bind_toObject_withKeyPath_options_(self, bind: str, object: Any, keyPath: "NSString" | str, options: "NSDictionary" | None) -> None: ...
	def unbind_(self, bind: str) -> None: ...
	def addObserver_forKeyPath_options_context_(self, observer: "NSObject", keyPath: str | "NSString", options: int, context: Any) -> None: ...
	def removeObserver_forKeyPath_context_(self, observer: "NSObject", keyPath: str | "NSString", context: Any) -> None: ...
	def removeObserver_forKeyPath_(self, observer: "NSObject", keyPath: str | "NSObject") -> None: ...


T = TypeVar("T", bound="NSObject")
KT = TypeVar("KT")
VT = TypeVar("VT")


class NSData(NSObject):
	@classmethod
	def dataWithContentsOfFile_(cls, path: str) -> Self: ...


class NSArray(NSObject, Generic[T]):
	def initWithObject_(self, value: Any) -> Self: ...
	def count(self) -> int: ...
	def objectAtIndex_(self, index: int) -> T: ...
	def __len__(self) -> int: ...
	@overload
	def __getitem__(self, index: int) -> T: ...
	@overload  # slicing returns a plain list, not an NSArray
	def __getitem__(self, index: slice) -> list[T]: ...
	def __iter__(self) -> Iterator[T]: ...
	@classmethod
	def arrayWithArray_(cls, array: list | "NSArray") -> Self: ...
	@classmethod
	def arrayWithContentsOfFile_(cls, path: str) -> Self: ...


class NSMutableArray(NSArray[T]):
	def addObject_(self, obj: Any) -> None: ...
	def append(self, obj: Any) -> None: ...


def NSClassFromString(name: str) -> Type[NSObject]: ...


class NSDate(NSObject):
	def initWithTimeIntervalSince1970_(self, interval: float) -> Self: ...
	@classmethod
	def date(cls) -> Self: ...
	@classmethod
	def dateWithTimeIntervalSinceNow_(cls, secs: float) -> Self: ...
	@classmethod
	def dateWithTimeIntervalSince1970_(cls, secs: float) -> Self: ...
	@classmethod
	def distantFuture(cls) -> Self: ...
	@classmethod
	def distantPast(cls) -> Self: ...
	def timeIntervalSince1970(self) -> float: ...
	def timeIntervalSinceNow(self) -> float: ...


class NSDictionary(Generic[KT, VT], NSObject):
	@classmethod
	def dictionary(cls) -> Self: ...
	def keysForObject_(self, obj: Any) -> list: ...
	@classmethod
	def dictionaryWithObject_forKey_(cls, objs: NSObject, keys: NSObject) -> Self: ...
	def __len__(self) -> int: ...
	def __iter__(self) -> Iterator[KT]: ...
	def items(self) -> Iterator[Tuple[KT, VT]]: ...
	def keys(self) -> Iterator[KT]: ...
	def values(self) -> Iterator[VT]: ...

class NSMutableDictionary(NSDictionary[KT, VT]):
	def setObject_forKey_(self, obj: Any, key: Any) -> None: ...
	def __setitem__(self, key: KT, value: VT) -> None: ...
	def initWithDictionary_copyItems_(self, dictionary: NSDictionary | dict, copyItems: bool) -> Self: ...
	def pop(self, key: Any, default: Any = ...) -> Any: ...


S = TypeVar("S")
_ES = TypeVar("_ES")  # method-scoped element type, so factories can infer it from their argument

class NSOrderedSet(Generic[S], Sequence[S]):
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, items: Iterable[S]) -> None: ...
	def __init__(self, items: Iterable[Any] | None = None) -> None: ...

	@classmethod
	def orderedSetWithArray_(cls, items: Iterable[_ES]) -> "NSOrderedSet[_ES]": ...

	# Core Objective-C API
	def count(self) -> int: ...
	def objectAtIndex_(self, index: int) -> S: ...
	def firstObject(self) -> S: ...
	def lastObject(self) -> S: ...
	def indexOfObject_(self, obj: S) -> int: ...  # NSNotFound if absent
	def containsObject_(self, obj: S) -> bool: ...
	# The set itself is not subscriptable; array() is the only indexed access.
	def array(self) -> "NSArray[Any]": ...

	# Python protocol methods
	def __len__(self) -> int: ...
	def __getitem__(self, index: int) -> S: ...
	def __iter__(self) -> Iterator[S]: ...

class NSMutableOrderedSet(NSOrderedSet[S]):
	# Narrowed from NSOrderedSet so the result stays mutable while keeping S.
	@classmethod
	def orderedSetWithArray_(cls, items: Iterable[_ES]) -> "NSMutableOrderedSet[_ES]": ...
	@classmethod
	def orderedSetWithCapacity_(cls, capacity: int) -> Self: ...

	# Adding & replacing
	def addObject_(self, obj: S) -> None: ...
	def addObjectsFromArray_(self, objects: Iterable[S]) -> None: ...
	def insertObject_atIndex_(self, obj: S, index: int) -> None: ...
	def setObject_atIndex_(self, obj: S, index: int) -> None: ...
	def replaceObjectAtIndex_withObject_(self, index: int, obj: S) -> None: ...

	# Reordering
	def exchangeObjectAtIndex_withObjectAtIndex_(self, idx1: int, idx2: int) -> None: ...
	def moveObjectsAtIndexes_toIndex_(self, indexes: "NSIndexSet", index: int) -> None: ...
	def sortUsingDescriptors_(self, descriptors: Iterable[Any]) -> None: ...

	# Removing
	def removeObject_(self, obj: S) -> None: ...
	def removeObjectAtIndex_(self, index: int) -> None: ...
	def removeObjectsInArray_(self, objects: Iterable[S]) -> None: ...
	def removeAllObjects(self) -> None: ...

	# Set operations, all in place
	def unionOrderedSet_(self, other: "NSOrderedSet[S]") -> None: ...
	def minusOrderedSet_(self, other: "NSOrderedSet[S]") -> None: ...
	def intersectOrderedSet_(self, other: "NSOrderedSet[S]") -> None: ...
	def unionSet_(self, other: set[S]) -> None: ...
	def minusSet_(self, other: set[S]) -> None: ...
	def intersectSet_(self, other: set[S]) -> None: ...


NSNotFound: int

class NSNull(NSObject):
	@classmethod
	def null(cls) -> "NSNull": ...

class NSNumber(NSObject):
	@classmethod
	def numberWithInt_(cls, number: int) -> "NSNumber": ...
	@classmethod
	def numberWithInteger_(cls, number: int) -> "NSNumber": ...
	@classmethod
	def numberWithFloat_(cls, number: float) -> "NSNumber": ...
	@classmethod
	def numberWithBool_(cls, number: bool) -> "NSNumber": ...
	def boolValue(self) -> bool: ...
	def floatValue(self) -> float: ...


class NSConcreteValue(NSObject):
	...


class NSString(NSObject):
	@classmethod
	def stringWithString_(cls, string: str | "NSString") -> "NSString": ...
	@classmethod
	def UUID(cls) -> "NSString": ...
	@classmethod
	def stringWithChar_(cls, char: int) -> "NSString": ...
	@classmethod
	def stringWithFormat_(cls: Type[T], format: "NSString", *args: Any) -> T: ...
	def sizeWithAttributes_(self, attributes: dict) -> NSSize: ...
	def drawInRect_withAttributes_(self, rect: NSRect, attributes: dict) -> None: ...
	def drawAtPoint_withAttributes_(self, pos: NSPoint, attributes: dict) -> None: ...
	def lastPathComponent(self) -> "NSString": ...
	@classmethod
	def drawTextAttributes_(cls, color: Any) -> dict: ...
	def drawAtPoint_color_alignment_handleSize_(self, pos: NSPoint, color: Any, aligment: int, handleSize: int) -> NSRect: ...


class NSAttributedString(NSObject):
	def initWithString_(self, string: str | NSString) -> Self: ...
	def initWithString_attributes_(self, string: str | NSString, attributes: dict | NSDictionary) -> Self: ...
	def drawAtPoint_alignment_(self, point: NSPointLike, alignment: int) -> None: ...
	def length(self) -> int: ...
	def size(self) -> NSSize: ...
	def drawAtPoint_(self, point: NSPointLike) -> None: ...
	@classmethod
	def attributedStringFromMarkdownString_(cls, markdown: str) -> Self: ...


class NSMutableAttributedString(NSAttributedString):
	def appendAttributedString_(self, string: NSAttributedString) -> None: ...


class NSIndexSet(NSObject):
	@classmethod
	def indexSetWithIndexesInRange_(cls, range: NSRangeLike) -> "NSIndexSet": ...


class NSAffineTransformStruct:
	m11: float
	m12: float
	m21: float
	m22: float
	tX: float
	tY: float

	@classmethod
	def __new__(
		cls,
		m11: float = 0,
		m12: float = 0,
		m21: float = 0,
		m22: float = 0,
		tX: float = 0,
		tY: float = 0,
	) -> Self: ...


class NSAffineTransform(NSObject):
	@classmethod
	def transform(cls) -> Self: ...
	def concat(self) -> None: ...
	def appendTransform_(self, transform: "NSAffineTransform") -> None: ...
	def translateXBy_yBy_(self, x: float, y: float) -> None: ...
	def scaleXBy_yBy_(self, x: float, y: float) -> None: ...
	def scaleBy_(self, scale: float) -> None: ...
	def rotateByDegrees_(self, angle: float) -> None: ...
	def transformStruct(self) -> NSAffineTransformStruct: ...
	def setTransformStruct_(self, ts: NSAffineTransformStruct | tuple) -> None: ...
	def transformPoint_(self, point: NSPointLike) -> NSPoint: ...
	def transformBezierPath_(self, bezierPath: NSBezierPath) -> None: ...
	# implemented in Glyphs
	def shearXBy_yBy_atCenter_(self, xShear: float, yShear: float, center: NSPointLike) -> None: ...
	def shearXBy_yBy_(self, xShear: float, yShear: float) -> None: ...
	def shearXBy_(self, xShear: float) -> None: ...
	def shearYBy_(self, yShear: float) -> None: ...
	def shearXBy_atCenter_(self, xShear: float, center: float) -> None: ...
	def shearYBy_atCenter_(self, yShear: float, center: float) -> None: ...

	def shift(self, shift: NSPointLike, center: NSPointLike | None = None) -> None: ...
	def scale(self, scale: NSPointLike, center: NSPointLike | None = None) -> None: ...
	def rotate(self, angle: float, center: NSPointLike | None = None) -> None: ...
	def skew(self, shift: tuple[float, float] | float, center: NSPointLike | None = None) -> None: ...

class NSURL(NSObject):
	@classmethod
	def URLWithString_(cls, path: str) -> "NSURL": ...
	@classmethod
	def fileURLWithPath_(cls, path: str | NSString) -> "NSURL": ...
	def path(self) -> str: ...


class NSIndexPath(NSObject):
	...


class NSNotificationCenter(NSObject):
	@classmethod
	def defaultCenter(cls) -> "NSNotificationCenter": ...
	def addObserver_selector_name_object_(self, callee: Any, selector: Any, callbackType: Any, obj: Any) -> None: ...
	def removeObserver_(self, callee: Any) -> None: ...
	def postNotificationName_object_(self, name: str, obj: Any) -> None: ...


class NSTimer(NSObject):
	@classmethod
	def scheduledTimerWithTimeInterval_target_selector_userInfo_repeats_(cls, dur: float, target: Any, sel: SEL, userInfo: dict | None, repeats: bool) -> Self: ...
	def invalidate(self) -> None: ...

class NSRunLoop(NSObject):
	@classmethod
	def currentRunLoop(cls) -> Self: ...
	@classmethod
	def mainRunLoop(cls) -> Self: ...
	def currentMode(self) -> str | None: ...  # None while the loop is not running
	def limitDateForMode_(self, mode: str) -> NSDate | None: ...
	def getCFRunLoop(self) -> Any: ...

	def addTimer_forMode_(self, timer: "NSTimer", mode: str) -> None: ...
	def run(self) -> None: ...  # blocks forever
	def runUntilDate_(self, limitDate: NSDate) -> None: ...
	def runMode_beforeDate_(self, mode: str, limitDate: NSDate) -> bool: ...
	def acceptInputForMode_beforeDate_(self, mode: str, limitDate: NSDate) -> None: ...
	def performBlock_(self, block: Any) -> None: ...

NSDefaultRunLoopMode: str
NSRunLoopCommonModes: str

def NSLog(log: str): ...

def NSHomeDirectory() -> str: ...
