# typings/Quartz.pyi

class CGContextRef:
	...

def UIGraphicsGetCurrentContext() -> CGContextRef | None: ...

def CGContextSaveGState(ctx: CGContextRef) -> None: ...
def CGContextRestoreGState(ctx: CGContextRef) -> None: ...

def CGContextSetAlpha(ctx: CGContextRef, alpha: float) -> None: ...
